### ISSUE TITLE
Remote store does not work with nix 2.17+

### ISSUE THREAD

**Issue by Artturin** [nixbuild/feedback#35]
`nix build --eval-store auto --store 'ssh-ng://eu.nixbuild.net' ".#bash"`
fails with
`error: unimplemented worker op: WopQueryDerivationOutputMap`

`wopQueryDerivationOutputMap` was renamed in commit https://github.com/NixOS/nix/commit/95eae0c002da5ef35e583b46a67818ebb95d3a1e nix pr https://github.com/NixOS/nix/pull/8547

```
$ nix --version
nix (Nix) 2.17.0
```

```
performing daemon worker op: 7
acquiring write lock on '/nix/var/nix/temproots/977391'
performing daemon worker op: 26
got tree '/nix/store/3w7wk0sbb9dgg384ngfk2l0bzgl56k8j-source' from 'git+file:///home/artturin/nixgits/my-nixpkgs'
checking access to '/nix/store/3w7wk0sbb9dgg384ngfk2l0bzgl56k8j-source/flake.nix'
evaluating file '/nix/store/3w7wk0sbb9dgg384ngfk2l0bzgl56k8j-source/flake.nix'
performing daemon worker op: 19
old lock file: {
  "nodes": {
    "root": {}
  },
  "root": "root",
  "version": 7
}
computing lock file node ''
new lock file: {
  "nodes": {
    "root": {}
  },
  "root": "root",
  "version": 7
}
trying flake output attribute 'packages.x86_64-linux.bash'
using cached attrset attribute ''
trying flake output attribute 'legacyPackages.x86_64-linux.bash'
trying flake output attribute 'bash'
using cached attrset attribute ''
using cached string attribute 'legacyPackages.x86_64-linux.bash.type'
using cached string attribute 'legacyPackages.x86_64-linux.bash.drvPath'
performing daemon worker op: 1
using cached integer attribute 'legacyPackages.x86_64-linux.bash.meta.priority'
using cached list of strings attribute 'legacyPackages.x86_64-linux.bash.meta.outputsToInstall'
OpenSSH_9.3p2, OpenSSL 3.0.9 30 May 2023
debug1: Reading configuration data /home/artturin/.ssh/config
debug1: /home/artturin/.ssh/config line 1: Applying options for *
debug1: /home/artturin/.ssh/config line 67: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 2: Applying options for eu.nixbuild.net
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: Control socket "/home/artturin/.ssh/master-artturin@eu.nixbuild.net:22" does not exist
debug1: Connecting to eu.nixbuild.net [148.251.182.157] port 22.
debug1: Connection established.
debug1: identity file /home/artturin/.ssh/nixbuild-key type 3
debug1: identity file /home/artturin/.ssh/nixbuild-key-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.3
debug1: Remote protocol version 2.0, remote software version hssh_0.1.0.0
debug1: compat_banner: no match: hssh_0.1.0.0
debug1: Authenticating to eu.nixbuild.net:22 as 'artturin'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:EgDuMV3L8raDZb6Csd9T4l4NRuh2rVNLbPz+63rcvAo
debug1: Host 'eu.nixbuild.net' is known and matches the ED25519 host key.
debug1: Found key in /etc/ssh/ssh_known_hosts:7
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: get_agent_identities: bound agent to hostkey
debug1: get_agent_identities: agent returned 2 keys
debug1: Will attempt key: ...
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: ...
debug1: Server accepts key: ...
Authenticated to eu.nixbuild.net ([148.251.182.157]:22) using "publickey".
debug1: channel 0: new session [client-session] (inactive timeout: 0)
debug1: Entering interactive session.
debug1: pledge: exec
debug1: Sending command: nix-daemon --stdio
don't know how to build these paths:
  /nix/store/jfi4am6v5qhqk0gjq5ycrpb6y8754qxf-bash-5.2-p15.drv
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
performing daemon worker op: 26
copying 0 paths...
starting pool of 23 threads
copying 0 paths...
starting pool of 23 threads
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
killing process 986440
error: unimplemented worker op: WopQueryDerivationOutputMap
```

**Comment by rickynils** [comment]
@Artturin Thanks for reporting this! We have been able to reproduce the issue. It seems like Nix 2.17 is now using the `QueryDerivationOutputMap` worker operation, which is was previously not used for these kinds of builds. nixbuild.net does not implement that operation, but we are working on fixing that.

**Comment by rickynils** [comment]
This is fixed now, `QueryDerivationOutputMap` has been implemented and deployed to nixbuild.net. I can now successfully run remote store builds with Nix 2.17. Can you verify this works for you, @Artturin?

**Comment by Artturin** [comment]
```
Authenticated to eu.nixbuild.net ([148.251.182.157]:22) using "publickey".
debug1: channel 0: new session [client-session] (inactive timeout: 0)
debug1: Entering interactive session.
debug1: pledge: exec
debug1: Sending command: nix-daemon --stdio
don't know how to build these paths:
  /nix/store/jfi4am6v5qhqk0gjq5ycrpb6y8754qxf-bash-5.2-p15.drv
copying 0 paths...
copying 0 paths...
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 37256, received 39808 bytes, in 1.3 seconds
Bytes per second: sent 29209.9, received 31210.8
debug1: Exit status 1
error: unimplemented worker op: WopQueryRealisation
```

still getting the same error

**Comment by rickynils** [comment]
@Artturin That looks like a different error (`WopQueryRealisation` vs `WopQueryDerivationOutputMap`). What command did you run to trigger the error?

**Comment by Artturin** [comment]
Oops yeah it's different

I ran `nix build --eval-store auto --store 'ssh-ng://eu.nixbuild.net' ".#bash"`

**Comment by Artturin** [comment]
You probably ran and fixed `nix-build --eval-store auto --store 'ssh-ng://eu.nixbuild.net' -A bash` and that works (didn't test before)

**Comment by rickynils** [comment]
@Artturin No, I ran `nix build`. Tested again with both commands and they work for me:

```
$ cd /tmp

$ git clone git@github.com:NixOS/nixpkgs.git
Cloning into 'nixpkgs'...
remote: Enumerating objects: 4209745, done.
remote: Counting objects: 100% (1189/1189), done.
remote: Compressing objects: 100% (539/539), done.
remote: Total 4209745 (delta 792), reused 903 (delta 601), pack-reused 4208556
Receiving objects: 100% (4209745/4209745), 3.40 GiB | 15.98 MiB/s, done.
Resolving deltas: 100% (2883856/2883856), done.
Updating files: 100% (36706/36706), done.

$ cd nixpkgs/

$ nix shell .#nixVersions.nix_2_17

$ nix --version
nix (Nix) 2.17.0

$ vim pkgs/applications/misc/hello/default.nix  # force rebuild by changing drv name

$ nix build --eval-store auto --store 'ssh-ng://eu.nixbuild.net' ".#hello"
warning: Git tree '/tmp/nixpkgs' is dirty

$ echo $?
0

$ vim pkgs/applications/misc/hello/default.nix  # force rebuild by changing drv name

$ nix-build --eval-store auto --store 'ssh-ng://eu.nixbuild.net' -A hello
don't know how to build these paths:
  /nix/store/bny0f94nqbp922f0alf8y84ciydm2ns6-hello-2.12.1-2.drv
copying 2 paths...
copying path '/nix/store/gs5hkcmv8drgaxz67lvd9gxpb28x5n3c-hello-2.12.1-2.tar.gz.drv' to 'ssh-ng://eu.nixbuild.net'...
copying path '/nix/store/bny0f94nqbp922f0alf8y84ciydm2ns6-hello-2.12.1-2.drv' to 'ssh-ng://eu.nixbuild.net'...
building '/nix/store/gs5hkcmv8drgaxz67lvd9gxpb28x5n3c-hello-2.12.1-2.tar.gz.drv'...
building '/nix/store/bny0f94nqbp922f0alf8y84ciydm2ns6-hello-2.12.1-2.drv'...
unpacking sources
.
.
.
stripping (with command strip and flags -S -p) in  /nix/store/6y2iqhxp79wr2hwycissb0wkcp7nkb45-hello-2.12.1-2/bin
/nix/store/6y2iqhxp79wr2hwycissb0wkcp7nkb45-hello-2.12.1-2
```

**Comment by Artturin** [comment]
Found the cause, it's the experimental feature `ca-derivations` 
`nix build --extra-experimental-features "ca-derivations" --eval-store auto --store 'ssh-ng://eu.nixbuild.net' ".#hello"`

**Comment by rickynils** [comment]
Ah, thanks @Artturin. I will try out the `ca-derivations` feature and see if I can reproduce it.
